package com.huoli.checkin.auto.code;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年05月08日<br>
 * generated by DB2JavaConvertor<br>
 */
public class AirlinesNormal {
    /* 代码 */
    private String code;
    /* 客服电话 */
    private String carePhone;
    /* 介绍 */
    private String introduce;
    private String fullName;
    private String shortName;
    private String serialNumber;
    private String reservePhone;
    private String website;
    /* 是否为国内，1为是，0为否 */
    private String internalFlag;
    /* 航空公司四字简称 */
    private String fourName;
    private String threeWordsCode;
    /* 英文名称 */
    private String enName;
    /* flightstats发布的航空公司电话 */
    private String fsPhone;
    /* 数据来源 */
    private String source;
    /* logo图片 */
    private String icon;
    private String imgcver;

    public String getCode(){
        return this.code;
    }
    public void setCode(String code){
        this.code = code;
    }
    public String getCarePhone(){
        return this.carePhone;
    }
    public void setCarePhone(String carePhone){
        this.carePhone = carePhone;
    }
    public String getIntroduce(){
        return this.introduce;
    }
    public void setIntroduce(String introduce){
        this.introduce = introduce;
    }
    public String getFullName(){
        return this.fullName;
    }
    public void setFullName(String fullName){
        this.fullName = fullName;
    }
    public String getShortName(){
        return this.shortName;
    }
    public void setShortName(String shortName){
        this.shortName = shortName;
    }
    public String getSerialNumber(){
        return this.serialNumber;
    }
    public void setSerialNumber(String serialNumber){
        this.serialNumber = serialNumber;
    }
    public String getReservePhone(){
        return this.reservePhone;
    }
    public void setReservePhone(String reservePhone){
        this.reservePhone = reservePhone;
    }
    public String getWebsite(){
        return this.website;
    }
    public void setWebsite(String website){
        this.website = website;
    }
    public String getInternalFlag(){
        return this.internalFlag;
    }
    public void setInternalFlag(String internalFlag){
        this.internalFlag = internalFlag;
    }
    public String getFourName(){
        return this.fourName;
    }
    public void setFourName(String fourName){
        this.fourName = fourName;
    }
    public String getThreeWordsCode(){
        return this.threeWordsCode;
    }
    public void setThreeWordsCode(String threeWordsCode){
        this.threeWordsCode = threeWordsCode;
    }
    public String getEnName(){
        return this.enName;
    }
    public void setEnName(String enName){
        this.enName = enName;
    }
    public String getFsPhone(){
        return this.fsPhone;
    }
    public void setFsPhone(String fsPhone){
        this.fsPhone = fsPhone;
    }
    public String getSource(){
        return this.source;
    }
    public void setSource(String source){
        this.source = source;
    }
    public String getIcon(){
        return this.icon;
    }
    public void setIcon(String icon){
        this.icon = icon;
    }
    public String getImgcver(){
        return this.imgcver;
    }
    public void setImgcver(String imgcver){
        this.imgcver = imgcver;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
