package com.huoli.checkin.auto.code;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年05月08日<br>
 * generated by DB2JavaConvertor<br>
 */
public class AirlinesNormalDao extends JdbcDaoSupport {
	/**行映射器*/
	private RowMapper <AirlinesNormal> rowMapper = new RowMapper<AirlinesNormal>() {
		public AirlinesNormal mapRow(ResultSet rs, int rowNum) throws SQLException {
            AirlinesNormal airlinesNormal = new AirlinesNormal();
            airlinesNormal.setCode(rs.getString("code"));
            airlinesNormal.setCarePhone(rs.getString("care_phone"));
            airlinesNormal.setIntroduce(rs.getString("introduce"));
            airlinesNormal.setFullName(rs.getString("full_name"));
            airlinesNormal.setShortName(rs.getString("short_name"));
            airlinesNormal.setSerialNumber(rs.getString("serial_number"));
            airlinesNormal.setReservePhone(rs.getString("reserve_phone"));
            airlinesNormal.setWebsite(rs.getString("website"));
            airlinesNormal.setInternalFlag(rs.getString("internal_flag"));
            airlinesNormal.setFourName(rs.getString("four_name"));
            airlinesNormal.setThreeWordsCode(rs.getString("three_words_code"));
            airlinesNormal.setEnName(rs.getString("en_name"));
            airlinesNormal.setFsPhone(rs.getString("fs_phone"));
            airlinesNormal.setSource(rs.getString("source"));
            airlinesNormal.setIcon(rs.getString("icon"));
            airlinesNormal.setImgcver(rs.getString("imgcver"));
			return airlinesNormal;
		}
	};
}