package com.huoli.checkin.auto.code;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年06月05日<br>
 * generated by CodeGenerator<br>
 */
public class AirportNormal {
    private String id;
    private String serialNumber;
    private String city;
    private String headCharacter;
    private String cityJianpin;
    private String cityPinyin;
    private String cityAlias;
    private String airportFullName;
    private String airportShortName;
    private String threeWordsCode;
    private String address;
    private String phone;
    private String distanceFromUrban;
    private String busPrice;
    private String subwayPrice;
    private String taxiPrice;
    private String airbuildingIntro;
    private String airbuildingPicture;
    private String geolat;
    private String geolong;
    private String geohash;
    private String cityGeolat;
    private String cityGeolong;
    private String fourWordsCode;
    private String cityname;
    /* 状态 0:新增，1：修改，2：删除 */
    private String status;

    public String getId(){
        return this.id;
    }
    public void setId(String id){
        this.id = id;
    }
    public String getSerialNumber(){
        return this.serialNumber;
    }
    public void setSerialNumber(String serialNumber){
        this.serialNumber = serialNumber;
    }
    public String getCity(){
        return this.city;
    }
    public void setCity(String city){
        this.city = city;
    }
    public String getHeadCharacter(){
        return this.headCharacter;
    }
    public void setHeadCharacter(String headCharacter){
        this.headCharacter = headCharacter;
    }
    public String getCityJianpin(){
        return this.cityJianpin;
    }
    public void setCityJianpin(String cityJianpin){
        this.cityJianpin = cityJianpin;
    }
    public String getCityPinyin(){
        return this.cityPinyin;
    }
    public void setCityPinyin(String cityPinyin){
        this.cityPinyin = cityPinyin;
    }
    public String getCityAlias(){
        return this.cityAlias;
    }
    public void setCityAlias(String cityAlias){
        this.cityAlias = cityAlias;
    }
    public String getAirportFullName(){
        return this.airportFullName;
    }
    public void setAirportFullName(String airportFullName){
        this.airportFullName = airportFullName;
    }
    public String getAirportShortName(){
        return this.airportShortName;
    }
    public void setAirportShortName(String airportShortName){
        this.airportShortName = airportShortName;
    }
    public String getThreeWordsCode(){
        return this.threeWordsCode;
    }
    public void setThreeWordsCode(String threeWordsCode){
        this.threeWordsCode = threeWordsCode;
    }
    public String getAddress(){
        return this.address;
    }
    public void setAddress(String address){
        this.address = address;
    }
    public String getPhone(){
        return this.phone;
    }
    public void setPhone(String phone){
        this.phone = phone;
    }
    public String getDistanceFromUrban(){
        return this.distanceFromUrban;
    }
    public void setDistanceFromUrban(String distanceFromUrban){
        this.distanceFromUrban = distanceFromUrban;
    }
    public String getBusPrice(){
        return this.busPrice;
    }
    public void setBusPrice(String busPrice){
        this.busPrice = busPrice;
    }
    public String getSubwayPrice(){
        return this.subwayPrice;
    }
    public void setSubwayPrice(String subwayPrice){
        this.subwayPrice = subwayPrice;
    }
    public String getTaxiPrice(){
        return this.taxiPrice;
    }
    public void setTaxiPrice(String taxiPrice){
        this.taxiPrice = taxiPrice;
    }
    public String getAirbuildingIntro(){
        return this.airbuildingIntro;
    }
    public void setAirbuildingIntro(String airbuildingIntro){
        this.airbuildingIntro = airbuildingIntro;
    }
    public String getAirbuildingPicture(){
        return this.airbuildingPicture;
    }
    public void setAirbuildingPicture(String airbuildingPicture){
        this.airbuildingPicture = airbuildingPicture;
    }
    public String getGeolat(){
        return this.geolat;
    }
    public void setGeolat(String geolat){
        this.geolat = geolat;
    }
    public String getGeolong(){
        return this.geolong;
    }
    public void setGeolong(String geolong){
        this.geolong = geolong;
    }
    public String getGeohash(){
        return this.geohash;
    }
    public void setGeohash(String geohash){
        this.geohash = geohash;
    }
    public String getCityGeolat(){
        return this.cityGeolat;
    }
    public void setCityGeolat(String cityGeolat){
        this.cityGeolat = cityGeolat;
    }
    public String getCityGeolong(){
        return this.cityGeolong;
    }
    public void setCityGeolong(String cityGeolong){
        this.cityGeolong = cityGeolong;
    }
    public String getFourWordsCode(){
        return this.fourWordsCode;
    }
    public void setFourWordsCode(String fourWordsCode){
        this.fourWordsCode = fourWordsCode;
    }
    public String getCityname(){
        return this.cityname;
    }
    public void setCityname(String cityname){
        this.cityname = cityname;
    }
    public String getStatus(){
        return this.status;
    }
    public void setStatus(String status){
        this.status = status;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
