package com.huoli.checkin.auto.code;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年10月23日<br>
 * generated by CodeGenerator<br>
 */
public class BookingSms {
    /* 自增ID */
    private Integer id;
    /* 渠道名称 */
    private String channel;
    /* 航班管家订单id */
    private String hbgjOrderId;
    /* 短信状态(0:未使用 1:已使用) */
    private Integer status;
    /* 发送方号码 */
    private String sendPhone;
    /* 接收方号码 */
    private String receivePhone;
    /* 短息内容 */
    private String message;
    /* 扩展字段 */
    private String extData;
    /* 创建时间 */
    private Date createTime;
    /* 修改时间 */
    private Date updateTime;

    public Integer getId(){
        return this.id;
    }
    public void setId(Integer id){
        this.id = id;
    }
    public String getChannel(){
        return this.channel;
    }
    public void setChannel(String channel){
        this.channel = channel;
    }
    public String getHbgjOrderId(){
        return this.hbgjOrderId;
    }
    public void setHbgjOrderId(String hbgjOrderId){
        this.hbgjOrderId = hbgjOrderId;
    }
    public Integer getStatus(){
        return this.status;
    }
    public void setStatus(Integer status){
        this.status = status;
    }
    public String getSendPhone(){
        return this.sendPhone;
    }
    public void setSendPhone(String sendPhone){
        this.sendPhone = sendPhone;
    }
    public String getReceivePhone(){
        return this.receivePhone;
    }
    public void setReceivePhone(String receivePhone){
        this.receivePhone = receivePhone;
    }
    public String getMessage(){
        return this.message;
    }
    public void setMessage(String message){
        this.message = message;
    }
    public String getExtData(){
        return this.extData;
    }
    public void setExtData(String extData){
        this.extData = extData;
    }
    public Date getCreateTime(){
        return this.createTime;
    }
    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }
    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
