package com.huoli.checkin.auto.code;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年10月23日<br>
 * generated by CodeGenerator<br>
 */
public class BookingSmsDao extends JdbcDaoSupport {
	/**行映射器*/
	private RowMapper <BookingSms> rowMapper = new RowMapper<BookingSms>() {
		public BookingSms mapRow(ResultSet rs, int rowNum) throws SQLException {
            BookingSms bookingSms = new BookingSms();
            bookingSms.setId(rs.getInt("id"));
            bookingSms.setChannel(rs.getString("channel"));
            bookingSms.setHbgjOrderId(rs.getString("hbgj_order_id"));
            bookingSms.setStatus(rs.getInt("status"));
            bookingSms.setSendPhone(rs.getString("send_phone"));
            bookingSms.setReceivePhone(rs.getString("receive_phone"));
            bookingSms.setMessage(rs.getString("message"));
            bookingSms.setExtData(rs.getString("ext_data"));
            bookingSms.setCreateTime(rs.getTimestamp("create_time"));
            bookingSms.setUpdateTime(rs.getTimestamp("update_time"));
			return bookingSms;
		}
	};
}