package com.huoli.checkin.auto.code;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年08月08日<br>
 * generated by CodeGenerator<br>
 */
public class CouponDetail {
    private Long id;
    /* 1-红包 2-优惠券 */
    private Integer type;
    /* 红包ID */
    private String couponId;
    /* 金额 */
    private String amount;
    /* 来源订单号 */
    private String from;
    /* 目的订单号 */
    private String to;
    /* 有效期开始时间 */
    private String expiryBeginDate;
    /* 有效期结束时间 */
    private String expiryEndDate;
    /* 优惠劵标题 */
    private String title;
    /* 红包或者优惠券用途描述 */
    private String desc;
    /* 规则描述 */
    private String rule;
    /* 扩展数据,使用json对象形式存储 */
    private String extData;
    /* 创建时间 */
    private Date createtime;
    /* 修改时间 */
    private Date updatetime;

    public Long getId(){
        return this.id;
    }
    public void setId(Long id){
        this.id = id;
    }
    public Integer getType(){
        return this.type;
    }
    public void setType(Integer type){
        this.type = type;
    }
    public String getCouponId(){
        return this.couponId;
    }
    public void setCouponId(String couponId){
        this.couponId = couponId;
    }
    public String getAmount(){
        return this.amount;
    }
    public void setAmount(String amount){
        this.amount = amount;
    }
    public String getFrom(){
        return this.from;
    }
    public void setFrom(String from){
        this.from = from;
    }
    public String getTo(){
        return this.to;
    }
    public void setTo(String to){
        this.to = to;
    }
    public String getExpiryBeginDate(){
        return this.expiryBeginDate;
    }
    public void setExpiryBeginDate(String expiryBeginDate){
        this.expiryBeginDate = expiryBeginDate;
    }
    public String getExpiryEndDate(){
        return this.expiryEndDate;
    }
    public void setExpiryEndDate(String expiryEndDate){
        this.expiryEndDate = expiryEndDate;
    }
    public String getTitle(){
        return this.title;
    }
    public void setTitle(String title){
        this.title = title;
    }
    public String getDesc(){
        return this.desc;
    }
    public void setDesc(String desc){
        this.desc = desc;
    }
    public String getRule(){
        return this.rule;
    }
    public void setRule(String rule){
        this.rule = rule;
    }
    public String getExtData(){
        return this.extData;
    }
    public void setExtData(String extData){
        this.extData = extData;
    }
    public Date getCreatetime(){
        return this.createtime;
    }
    public void setCreatetime(Date createtime){
        this.createtime = createtime;
    }
    public Date getUpdatetime(){
        return this.updatetime;
    }
    public void setUpdatetime(Date updatetime){
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
