package com.huoli.checkin.auto.code;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年06月05日<br>
 * generated by DB2JavaConvertor<br>
 */
public class FlyAirportTblDao extends JdbcDaoSupport {
	/**行映射器*/
	private RowMapper <FlyAirportTbl> rowMapper = new RowMapper<FlyAirportTbl>() {
		public FlyAirportTbl mapRow(ResultSet rs, int rowNum) throws SQLException {
            FlyAirportTbl flyAirportTbl = new FlyAirportTbl();
            flyAirportTbl.setId(rs.getString("id"));
            flyAirportTbl.setLatitude(rs.getString("latitude"));
            flyAirportTbl.setLongtitude(rs.getString("longtitude"));
            flyAirportTbl.setJindu(rs.getString("jindu"));
            flyAirportTbl.setCity(rs.getString("city"));
            flyAirportTbl.setPinyin(rs.getString("pinyin"));
            flyAirportTbl.setCode(rs.getString("code"));
            flyAirportTbl.setFullname(rs.getString("fullname"));
            flyAirportTbl.setShortname(rs.getString("shortname"));
            flyAirportTbl.setAddress(rs.getString("address"));
			return flyAirportTbl;
		}
	};
}