package com.huoli.checkin.auto.code;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年06月05日<br>
 * generated by DB2JavaConvertor<br>
 */
public class FlyAirportTbl {
    private String id;
    private String latitude;
    private String longtitude;
    private String jindu;
    private String city;
    private String pinyin;
    private String code;
    private String fullname;
    private String shortname;
    private String address;

    public String getId(){
        return this.id;
    }
    public void setId(String id){
        this.id = id;
    }
    public String getLatitude(){
        return this.latitude;
    }
    public void setLatitude(String latitude){
        this.latitude = latitude;
    }
    public String getLongtitude(){
        return this.longtitude;
    }
    public void setLongtitude(String longtitude){
        this.longtitude = longtitude;
    }
    public String getJindu(){
        return this.jindu;
    }
    public void setJindu(String jindu){
        this.jindu = jindu;
    }
    public String getCity(){
        return this.city;
    }
    public void setCity(String city){
        this.city = city;
    }
    public String getPinyin(){
        return this.pinyin;
    }
    public void setPinyin(String pinyin){
        this.pinyin = pinyin;
    }
    public String getCode(){
        return this.code;
    }
    public void setCode(String code){
        this.code = code;
    }
    public String getFullname(){
        return this.fullname;
    }
    public void setFullname(String fullname){
        this.fullname = fullname;
    }
    public String getShortname(){
        return this.shortname;
    }
    public void setShortname(String shortname){
        this.shortname = shortname;
    }
    public String getAddress(){
        return this.address;
    }
    public void setAddress(String address){
        this.address = address;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
