package com.huoli.checkin.auto.code;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年05月25日<br>
 * generated by DB2JavaConvertor<br>
 */
public class ManualPayRecord {
    private Integer id;
    /* 渠道,来源于订单模块 */
    private String channel;
    /* 航班管家订单号,来自订单模块 */
    private String orderId;
    /* 外部订单号,来自航司官网 */
    private String outOrderNo;
    /* 支付链接 */
    private String payUrl;
    /* 状态(0:未认领,1:已认领,2:已完成) */
    private Integer status;
    /* 锁定账户名称 */
    private String lockUser;
    /* 锁定时间 */
    private Date lockTime;
    /* 创建时间 */
    private Date createTime;
    /* 修改时间 */
    private Date updateTime;
    /* 扩展字段数据 */
    private String extData;

    public Integer getId(){
        return this.id;
    }
    public void setId(Integer id){
        this.id = id;
    }
    public String getChannel(){
        return this.channel;
    }
    public void setChannel(String channel){
        this.channel = channel;
    }
    public String getOrderId(){
        return this.orderId;
    }
    public void setOrderId(String orderId){
        this.orderId = orderId;
    }
    public String getOutOrderNo(){
        return this.outOrderNo;
    }
    public void setOutOrderNo(String outOrderNo){
        this.outOrderNo = outOrderNo;
    }
    public String getPayUrl(){
        return this.payUrl;
    }
    public void setPayUrl(String payUrl){
        this.payUrl = payUrl;
    }
    public Integer getStatus(){
        return this.status;
    }
    public void setStatus(Integer status){
        this.status = status;
    }
    public String getLockUser(){
        return this.lockUser;
    }
    public void setLockUser(String lockUser){
        this.lockUser = lockUser;
    }
    public Date getLockTime(){
        return this.lockTime;
    }
    public void setLockTime(Date lockTime){
        this.lockTime = lockTime;
    }
    public Date getCreateTime(){
        return this.createTime;
    }
    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }
    public Date getUpdateTime(){
        return this.updateTime;
    }
    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }
    public String getExtData(){
        return this.extData;
    }
    public void setExtData(String extData){
        this.extData = extData;
    }

    @Override
    public String toString() {
          return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
