package com.huoli.checkin.auto.code;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年05月25日<br>
 * generated by DB2JavaConvertor<br>
 */
public class ManualPayRecordDao extends JdbcDaoSupport {
	/**行映射器*/
	private RowMapper <ManualPayRecord> rowMapper = new RowMapper<ManualPayRecord>() {
		public ManualPayRecord mapRow(ResultSet rs, int rowNum) throws SQLException {
            ManualPayRecord manualPayRecord = new ManualPayRecord();
            manualPayRecord.setId(rs.getInt("id"));
            manualPayRecord.setChannel(rs.getString("channel"));
            manualPayRecord.setOrderId(rs.getString("order_id"));
            manualPayRecord.setOutOrderNo(rs.getString("out_order_no"));
            manualPayRecord.setPayUrl(rs.getString("pay_url"));
            manualPayRecord.setStatus(rs.getInt("status"));
            manualPayRecord.setLockUser(rs.getString("lock_user"));
            manualPayRecord.setLockTime(rs.getTimestamp("lock_time"));
            manualPayRecord.setCreateTime(rs.getTimestamp("create_time"));
            manualPayRecord.setUpdateTime(rs.getTimestamp("update_time"));
            manualPayRecord.setExtData(rs.getString("ext_data"));
			return manualPayRecord;
		}
	};
}