package com.huoli.checkin.auto.code;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年06月15日<br>
 * generated by CodeGenerator<br>
 */
public class PayUser {
    /* 主键 */
    private Integer id;
    /* 用户航班管家的phoneid */
    private String phoneId;
    /* 用户航班管家的设备id */
    private String uid;
    /* 用户手机号码 */
    private String mobile;
    /* 用户中文姓名 */
    private String name;
    /* 支付宝账号 */
    private String alipayUser;
    /* 状态(0:不可用 1:可用) */
    private Integer status;
    /* 使用次数 */
    private Integer used;
    /* 创建时间 */
    private Date createTime;
    /* 修改时间 */
    private Date updateTime;
    /* 扩展数据,使用json对象形式存储,存放邮箱等关联信息 */
    private String extData;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhoneId() {
        return this.phoneId;
    }

    public void setPhoneId(String phoneId) {
        this.phoneId = phoneId;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlipayUser() {
        return this.alipayUser;
    }

    public void setAlipayUser(String alipayUser) {
        this.alipayUser = alipayUser;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getUsed() {
        return this.used;
    }

    public void setUsed(Integer used) {
        this.used = used;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getExtData() {
        return this.extData;
    }

    public void setExtData(String extData) {
        this.extData = extData;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
