package com.huoli.checkin.auto.code;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.support.JdbcDaoSupport;

/**
 * <br>
 * 版权: Copyright (c) 2011-2017<br>
 * 公司: 北京活力天汇<br>
 * 
 * @author: 廖浩<br>
 * @date: 2017年06月15日<br>
 * generated by CodeGenerator<br>
 */
public class PayUserDao extends JdbcDaoSupport {
    /**行映射器*/
    private RowMapper<PayUser> rowMapper = new RowMapper<PayUser>() {
        public PayUser mapRow(ResultSet rs, int rowNum) throws SQLException {
            PayUser payUser = new PayUser();
            payUser.setId(rs.getInt("id"));
            payUser.setPhoneId(rs.getString("phone_id"));
            payUser.setUid(rs.getString("uid"));
            payUser.setMobile(rs.getString("mobile"));
            payUser.setName(rs.getString("name"));
            payUser.setAlipayUser(rs.getString("alipay_user"));
            payUser.setStatus(rs.getInt("status"));
            payUser.setUsed(rs.getInt("used"));
            payUser.setCreateTime(rs.getTimestamp("create_time"));
            payUser.setUpdateTime(rs.getTimestamp("update_time"));
            payUser.setExtData(rs.getString("ext_data"));
            return payUser;
        }
    };
}